Update WRT-CORE.yml

diff --git a/.github/workflows/WRT-CORE.yml b/.github/workflows/WRT-CORE.yml
--- a/.github/workflows/WRT-CORE.yml
+++ b/.github/workflows/WRT-CORE.yml
@@ -74,6 +74,14 @@ jobs:
           swap-storage: true
           tool-cache: true
 
+      - name: Remove Unnecessary Packages
+        run: |
+          if [ -n "$pkgs" ]; then
+            sudo apt-get remove --autoremove -y $pkgs || echo "::warning::The command [sudo apt-get remove -y] failed to complete successfully. Proceeding..."
+          else
+            echo "::warning::No packages to remove."
+          fi
+
       - name: Initialization Environment
         env:
           DEBIAN_FRONTEND: noninteractive
